### PR TITLE
Fixing table name parsing

### PR DESCRIPTION
**Pull request by cgaspard**
I've changed your parsing function a bit to use a regex and return a full breakdown of the table name, schema and database if present.

I created this js fiddle to demonstration the functionality.   

I am unable to build this extensions since I don't have a full env setup to do so.

https://jsfiddle.net/cgaspard/pqymw7de/

### CODE REVIEW

**Comment by LycanII** [comment]
Awesome work @cgaspard , thanks so much, 
I'll check it out and add if it checks out.

**Comment by cgaspard** [comment]
Okay this doesn't actually solve the problem.    It may be better at parsing the table name though.   I'll see if i can figure out what it think the table doesn't exist and update the pull request in a bit.

**Comment by cgaspard** [comment]
So what I did was just disabled the check to verify the table exists.   This function was actually what is causing the problem.    I haven't looked at why yet.   But overall the extension behaves well and shows an error message if you try to run a query that errors so I think its okay.

I'll see if I can trouble shoot the problem some more when I have time.

This is the change I made locally inside generalFuncs.js.

image

**Comment by cgaspard** [comment]
In this version I've just commented out the check to see if the table exists.   I think this approach is okay for now because the error notification will pop up if the sql the user select doesn't actually return any values.

I'll see if I can correct the tableExists function at some point.   But you may want to publish this version of the extension since the user experience is acceptable, at least to me it seems to be.

**Review by LycanII — APPROVED** [review]
LGTM :)
i only added a few adjustments to your code , also i think we still need to check in db to be sure table actually exists . 
Thanks so much for contributing!

**Comment by LycanII** [comment]
> So what I did was just disabled the check to verify the table exists. This function was actually what is causing the problem. I haven't looked at why yet. But overall the extension behaves well and shows an error message if you try to run a query that errors so I think its okay.
> 
> I'll see if I can trouble shoot the problem some more when I have time.
> 
> This is the change I made locally inside generalFuncs.js.
> 
> image

I see what you mean, yes, am not sure why it fails sometimes.
I will check it too , in the meantime I think we still need to check from db.

**Pull request merged**
